name: Build Radio Dashboard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtk-3-dev libglib2.0-dev libhamlib-dev libpulse-dev libsndfile1-dev

      - name: Build Project
        run: make all
